# Polars Exercises

This notebook contains ten exercises for data manipulation with Polars.
Each exercise includes hints, an answer, and an optional extension for when you want more of a challenge.

## Resources

* [Polars documentation](https://docs.pola.rs)
* [Cheat Sheet (PDF)](https://franzdiebold.github.io/polars-cheat-sheet/Polars_cheat_sheet.pdf)

In [1]:
import polars as pl

## Read data

You'll be working with a dataset of open-source project metrics.
It contains daily activity counts (downloads, issues, PRs, forks) and totals (views, likes) from sources like GitHub, PyPI, and CRAN.

To keep things manageable, you'll filter to PyPI download counts for a few Python packages.

In [2]:
metrics = pl.read_parquet("data/metrics.parquet")
metrics

shape: (949_438, 7)
┌─────────────────┬────────┬────────────────┬────────────────┬────────────┬───────┬────────────────┐
│ project         ┆ source ┆ target         ┆ metric         ┆ date       ┆ value ┆ extra          │
│ ---             ┆ ---    ┆ ---            ┆ ---            ┆ ---        ┆ ---   ┆ ---            │
│ str             ┆ str    ┆ str            ┆ str            ┆ date       ┆ i64   ┆ binary         │
╞═════════════════╪════════╪════════════════╪════════════════╪════════════╪═══════╪════════════════╡
│ a-flexdashboard ┆ github ┆ rstudio/a-flex ┆ daily_forks    ┆ 2021-01-07 ┆ 1     ┆ null           │
│ -for-google-ana ┆        ┆ dashboard-for- ┆                ┆            ┆       ┆                │
│ …               ┆        ┆ go…            ┆                ┆            ┆       ┆                │
│ a-flexdashboard ┆ github ┆ rstudio/a-flex ┆ daily_forks    ┆ 2021-07-17 ┆ 1     ┆ null           │
│ -for-google-ana ┆        ┆ dashboard-for- ┆                ┆            ┆       ┆                │
│ …               ┆        ┆ go…            ┆                ┆            ┆       ┆                │
│ a-flexdashboard ┆ github ┆ rstudio/a-flex ┆ daily_forks    ┆ 2022-01-10 ┆ 1     ┆ null           │
│ -for-google-ana ┆        ┆ dashboard-for- ┆                ┆            ┆       ┆                │
│ …               ┆        ┆ go…            ┆                ┆            ┆       ┆                │
│ academy-apprent ┆ github ┆ rstudio/academ ┆ daily_issues_o ┆ 2026-04-23 ┆ 1     ┆ null           │
│ iceship-diagnos ┆        ┆ y-apprenticesh ┆ pened          ┆            ┆       ┆                │
│ …               ┆        ┆ ip…            ┆                ┆            ┆       ┆                │
│ academy-apprent ┆ github ┆ rstudio/academ ┆ daily_prs_merg ┆ 2026-07-06 ┆ 1     ┆ null           │
│ iceship-diagnos ┆        ┆ y-apprenticesh ┆ ed             ┆            ┆       ┆                │
│ …               ┆        ┆ ip…            ┆                ┆            ┆       ┆                │
│ …               ┆ …      ┆ …              ┆ …              ┆ …          ┆ …     ┆ …              │
│ zd-cli          ┆ github ┆ posit-dev/zd-c ┆ daily_prs_open ┆ 2023-08-03 ┆ 1     ┆ null           │
│                 ┆        ┆ li             ┆ ed             ┆            ┆       ┆                │
│ zd-cli          ┆ github ┆ posit-dev/zd-c ┆ total_reaction ┆ 2026-07-27 ┆ 0     ┆ b"{"ref":"1"}" │
│                 ┆        ┆ li             ┆ s              ┆            ┆       ┆                │
│ zd-cli          ┆ github ┆ posit-dev/zd-c ┆ total_reaction ┆ 2026-07-27 ┆ 0     ┆ b"{"ref":"4"}" │
│                 ┆        ┆ li             ┆ s              ┆            ┆       ┆                │
│ zd-cli          ┆ github ┆ posit-dev/zd-c ┆ total_reaction ┆ 2026-07-27 ┆ 0     ┆ b"{"ref":"2"}" │
│                 ┆        ┆ li             ┆ s              ┆            ┆       ┆                │
│ zd-cli          ┆ github ┆ posit-dev/zd-c ┆ total_reaction ┆ 2026-07-27 ┆ 0     ┆ b"{"ref":"3"}" │
│                 ┆        ┆ li             ┆ s              ┆            ┆       ┆                │
└─────────────────┴────────┴────────────────┴────────────────┴────────────┴───────┴────────────────┘

In [3]:
downloads = metrics.filter(
    pl.col("source") == "pypi",
    pl.col("metric") == "daily_downloads",
)
downloads

shape: (2_899, 7)
┌──────────────┬────────┬─────────┬─────────────────┬────────────┬───────┬────────┐
│ project      ┆ source ┆ target  ┆ metric          ┆ date       ┆ value ┆ extra  │
│ ---          ┆ ---    ┆ ---     ┆ ---             ┆ ---        ┆ ---   ┆ ---    │
│ str          ┆ str    ┆ str     ┆ str             ┆ date       ┆ i64   ┆ binary │
╞══════════════╪════════╪═════════╪═════════════════╪════════════╪═══════╪════════╡
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-04 ┆ 1650  ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-05 ┆ 1626  ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-06 ┆ 514   ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-07 ┆ 456   ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-08 ┆ 339   ┆ null   │
│ …            ┆ …      ┆ …       ┆ …               ┆ …          ┆ …     ┆ …      │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-19 ┆ 10825 ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-20 ┆ 10435 ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-21 ┆ 12795 ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-22 ┆ 9257  ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-23 ┆ 8291  ┆ null   │
└──────────────┴────────┴─────────┴─────────────────┴────────────┴───────┴────────┘

## Exercise 1: Selecting columns

Select only the `project`, `date`, and `value` columns from `downloads`.
Then write a second query that selects all columns *except* `extra`.

**Optional extension:**

* Use `polars.selectors` (e.g., `cs.string()`, `cs.temporal()`) to select all columns that have a string or temporal data type.

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Use <code>downloads.select(...)</code> with column names as strings.<br>
&bull; To exclude a column, look at <code>pl.exclude()</code>.<br>
&bull; For the extension, <code>import polars.selectors as cs</code> and combine selectors with <code>|</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.select("project", "date", "value")</pre>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.select(pl.exclude("extra"))</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">import polars.selectors as cs

downloads.select(cs.string() | cs.temporal())</pre>
</div>

In [5]:
downloads.select(
    pl.col('project'),
    pl.col('date'),
    pl.col('value')
)

shape: (2_899, 3)
┌──────────────┬────────────┬───────┐
│ project      ┆ date       ┆ value │
│ ---          ┆ ---        ┆ ---   │
│ str          ┆ date       ┆ i64   │
╞══════════════╪════════════╪═══════╡
│ chatlas      ┆ 2025-06-04 ┆ 1650  │
│ chatlas      ┆ 2025-06-05 ┆ 1626  │
│ chatlas      ┆ 2025-06-06 ┆ 514   │
│ chatlas      ┆ 2025-06-07 ┆ 456   │
│ chatlas      ┆ 2025-06-08 ┆ 339   │
│ …            ┆ …          ┆ …     │
│ shiny-python ┆ 2026-08-19 ┆ 10825 │
│ shiny-python ┆ 2026-08-20 ┆ 10435 │
│ shiny-python ┆ 2026-08-21 ┆ 12795 │
│ shiny-python ┆ 2026-08-22 ┆ 9257  │
│ shiny-python ┆ 2026-08-23 ┆ 8291  │
└──────────────┴────────────┴───────┘

In [6]:
downloads.select(
    pl.exclude('extra')
)

shape: (2_899, 6)
┌──────────────┬────────┬─────────┬─────────────────┬────────────┬───────┐
│ project      ┆ source ┆ target  ┆ metric          ┆ date       ┆ value │
│ ---          ┆ ---    ┆ ---     ┆ ---             ┆ ---        ┆ ---   │
│ str          ┆ str    ┆ str     ┆ str             ┆ date       ┆ i64   │
╞══════════════╪════════╪═════════╪═════════════════╪════════════╪═══════╡
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-04 ┆ 1650  │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-05 ┆ 1626  │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-06 ┆ 514   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-07 ┆ 456   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-08 ┆ 339   │
│ …            ┆ …      ┆ …       ┆ …               ┆ …          ┆ …     │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-19 ┆ 10825 │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-20 ┆ 10435 │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-21 ┆ 12795 │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-22 ┆ 9257  │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-23 ┆ 8291  │
└──────────────┴────────┴─────────┴─────────────────┴────────────┴───────┘

## Exercise 2: Filtering rows

Each of the following three code snippets contains a common beginner mistake.
Uncomment each one, observe the error, and fix it.

In [9]:
# Snippet 1: Find plotnine downloads above 50,000
downloads.filter((pl.col("project") == "plotnine") & (pl.col("value") > 50_000))

shape: (439, 7)
┌──────────┬────────┬──────────┬─────────────────┬────────────┬────────┬────────┐
│ project  ┆ source ┆ target   ┆ metric          ┆ date       ┆ value  ┆ extra  │
│ ---      ┆ ---    ┆ ---      ┆ ---             ┆ ---        ┆ ---    ┆ ---    │
│ str      ┆ str    ┆ str      ┆ str             ┆ date       ┆ i64    ┆ binary │
╞══════════╪════════╪══════════╪═════════════════╪════════════╪════════╪════════╡
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-04 ┆ 177616 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-05 ┆ 77103  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-06 ┆ 65174  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-07 ┆ 50674  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-09 ┆ 90100  ┆ null   │
│ …        ┆ …      ┆ …        ┆ …               ┆ …          ┆ …      ┆ …      │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-19 ┆ 132296 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-20 ┆ 104746 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-21 ┆ 103189 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-22 ┆ 80683  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-23 ┆ 71368  ┆ null   │
└──────────┴────────┴──────────┴─────────────────┴────────────┴────────┴────────┘

In [10]:
# Snippet 2: Find rows with more than 50,000 downloads
downloads.filter(pl.col("value") > 50_000)

shape: (439, 7)
┌──────────┬────────┬──────────┬─────────────────┬────────────┬────────┬────────┐
│ project  ┆ source ┆ target   ┆ metric          ┆ date       ┆ value  ┆ extra  │
│ ---      ┆ ---    ┆ ---      ┆ ---             ┆ ---        ┆ ---    ┆ ---    │
│ str      ┆ str    ┆ str      ┆ str             ┆ date       ┆ i64    ┆ binary │
╞══════════╪════════╪══════════╪═════════════════╪════════════╪════════╪════════╡
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-04 ┆ 177616 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-05 ┆ 77103  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-06 ┆ 65174  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-07 ┆ 50674  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2025-06-09 ┆ 90100  ┆ null   │
│ …        ┆ …      ┆ …        ┆ …               ┆ …          ┆ …      ┆ …      │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-19 ┆ 132296 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-20 ┆ 104746 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-21 ┆ 103189 ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-22 ┆ 80683  ┆ null   │
│ plotnine ┆ pypi   ┆ plotnine ┆ daily_downloads ┆ 2026-08-23 ┆ 71368  ┆ null   │
└──────────┴────────┴──────────┴─────────────────┴────────────┴────────┴────────┘

In [11]:
# Snippet 3: Filter the full metrics DataFrame to PyPI downloads
metrics.filter((pl.col("source") == "pypi") & (pl.col("metric") == "daily_downloads"))

shape: (2_899, 7)
┌──────────────┬────────┬─────────┬─────────────────┬────────────┬───────┬────────┐
│ project      ┆ source ┆ target  ┆ metric          ┆ date       ┆ value ┆ extra  │
│ ---          ┆ ---    ┆ ---     ┆ ---             ┆ ---        ┆ ---   ┆ ---    │
│ str          ┆ str    ┆ str     ┆ str             ┆ date       ┆ i64   ┆ binary │
╞══════════════╪════════╪═════════╪═════════════════╪════════════╪═══════╪════════╡
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-04 ┆ 1650  ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-05 ┆ 1626  ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-06 ┆ 514   ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-07 ┆ 456   ┆ null   │
│ chatlas      ┆ pypi   ┆ chatlas ┆ daily_downloads ┆ 2025-06-08 ┆ 339   ┆ null   │
│ …            ┆ …      ┆ …       ┆ …               ┆ …          ┆ …     ┆ …      │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-19 ┆ 10825 ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-20 ┆ 10435 ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-21 ┆ 12795 ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-22 ┆ 9257  ┆ null   │
│ shiny-python ┆ pypi   ┆ shiny   ┆ daily_downloads ┆ 2026-08-23 ┆ 8291  ┆ null   │
└──────────────┴────────┴─────────┴─────────────────┴────────────┴───────┴────────┘

**Optional extension:**

* Write a filter from scratch that finds rows where the project is `"plotnine"` or `"great-tables"`, the value is between 10,000 and 100,000, and the date is in 2026.

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Snippet 1: Python's <code>and</code> keyword doesn't work with Polars expressions. Use <code>&amp;</code> instead, and wrap each condition in parentheses.<br>
&bull; Snippet 2: <code>"value"</code> is just a string. You need <code>pl.col("value")</code> to reference the column.<br>
&bull; Snippet 3: <code>&amp;</code> has higher precedence than <code>==</code>. Add parentheses around each comparison. Alternatively, you can pass multiple conditions as separate arguments to <code>filter()</code>.<br>
&bull; For the extension, look at <code>.is_in()</code>, <code>.is_between()</code>, and <code>.dt.year()</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
Snippet 1:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.filter((pl.col("project") == "plotnine") &amp; (pl.col("value") &gt; 50_000))</pre>
Snippet 2:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.filter(pl.col("value") &gt; 50_000)</pre>
Snippet 3:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">metrics.filter(
    (pl.col("source") == "pypi") &amp; (pl.col("metric") == "daily_downloads")
)</pre>
Or, even better, pass conditions as separate arguments:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">metrics.filter(
    pl.col("source") == "pypi",
    pl.col("metric") == "daily_downloads",
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.filter(
    pl.col("project").is_in(["plotnine", "great-tables"]),
    pl.col("value").is_between(10_000, 100_000),
    pl.col("date").dt.year() == 2026,
)</pre>
</div>

In [14]:
#  project is "plotnine" or "great-tables"
# the value is between 10,000 
# and 100,000, and the date is in 2026.
metrics.filter(
    (pl.col('project').is_in(('plotnine', 'great-tables'))) &
    pl.col('value').is_between(10000, 100000) &
    (pl.col('date').dt.year() == 2026)
)

shape: (271, 7)
┌──────────────┬────────┬──────────────┬─────────────────┬────────────┬───────┬────────┐
│ project      ┆ source ┆ target       ┆ metric          ┆ date       ┆ value ┆ extra  │
│ ---          ┆ ---    ┆ ---          ┆ ---             ┆ ---        ┆ ---   ┆ ---    │
│ str          ┆ str    ┆ str          ┆ str             ┆ date       ┆ i64   ┆ binary │
╞══════════════╪════════╪══════════════╪═════════════════╪════════════╪═══════╪════════╡
│ great-tables ┆ pypi   ┆ great-tables ┆ daily_downloads ┆ 2026-01-02 ┆ 16381 ┆ null   │
│ great-tables ┆ pypi   ┆ great-tables ┆ daily_downloads ┆ 2026-01-05 ┆ 12526 ┆ null   │
│ great-tables ┆ pypi   ┆ great-tables ┆ daily_downloads ┆ 2026-01-06 ┆ 16222 ┆ null   │
│ great-tables ┆ pypi   ┆ great-tables ┆ daily_downloads ┆ 2026-01-07 ┆ 14893 ┆ null   │
│ great-tables ┆ pypi   ┆ great-tables ┆ daily_downloads ┆ 2026-01-08 ┆ 17398 ┆ null   │
│ …            ┆ …      ┆ …            ┆ …               ┆ …          ┆ …     ┆ …      │
│ plotnine     ┆ pypi   ┆ plotnine     ┆ daily_downloads ┆ 2026-08-09 ┆ 81519 ┆ null   │
│ plotnine     ┆ pypi   ┆ plotnine     ┆ daily_downloads ┆ 2026-08-15 ┆ 87979 ┆ null   │
│ plotnine     ┆ pypi   ┆ plotnine     ┆ daily_downloads ┆ 2026-08-16 ┆ 81885 ┆ null   │
│ plotnine     ┆ pypi   ┆ plotnine     ┆ daily_downloads ┆ 2026-08-22 ┆ 80683 ┆ null   │
│ plotnine     ┆ pypi   ┆ plotnine     ┆ daily_downloads ┆ 2026-08-23 ┆ 71368 ┆ null   │
└──────────────┴────────┴──────────────┴─────────────────┴────────────┴───────┴────────┘

## Exercise 3: Sorting rows

Find the 10 days with the highest download count across all projects.
Show the project name, date, and value.

**Optional extension:**

* Can you achieve the same result using `top_k()` instead of `sort()` + `head()`?
* Sort `downloads` by `project` ascending *and* `value` descending at the same time.

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Use <code>.sort()</code> with <code>descending=True</code> followed by <code>.head(10)</code>.<br>
&bull; <code>top_k()</code> takes <code>k</code> as the first argument and <code>by</code> as the second.<br>
&bull; When sorting by multiple columns, pass a list to <code>descending</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.sort("value", descending=True).head(10)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.top_k(10, by="value")</pre>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.sort("project", "value", descending=[False, True])</pre>
</div>

## Exercise 4: Creating new columns

The code below selects three columns from `downloads`.
Extend it by adding a new column called `value_thousands` that shows the download count in thousands, rounded to one decimal place.

In [ ]:
downloads.select("project", "date", "value")

**Optional extension:**

* Add a `popularity` column that categorizes each day as `"viral"` (value > 100,000), `"popular"` (value > 10,000), or `"normal"` (everything else).

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Chain <code>.with_columns()</code> after the <code>.select()</code>.<br>
&bull; Use <code>(pl.col("value") / 1000).round(1)</code> for the calculation.<br>
&bull; For the extension, use <code>pl.when(...).then(...).when(...).then(...).otherwise(...)</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    downloads
    .select("project", "date", "value")
    .with_columns(
        value_thousands=(pl.col("value") / 1000).round(1),
    )
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    downloads
    .select("project", "date", "value")
    .with_columns(
        value_thousands=(pl.col("value") / 1000).round(1),
        popularity=pl.when(pl.col("value") &gt; 100_000)
        .then(pl.lit("viral"))
        .when(pl.col("value") &gt; 10_000)
        .then(pl.lit("popular"))
        .otherwise(pl.lit("normal")),
    )
)</pre>
</div>

## Exercise 5: Temporal expressions

Starting from `downloads`, create a DataFrame with the columns `project`, `date`, `value`, plus three new columns: `year`, `month`, and `weekday` (where Monday = 1).

**Optional extension:**

* Which day of the week has the highest *average* downloads across all projects?

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Use the <code>.dt</code> namespace to access temporal methods: <code>.dt.year()</code>, <code>.dt.month()</code>, <code>.dt.weekday()</code>.<br>
&bull; For the extension, combine <code>with_columns()</code>, <code>group_by()</code>, <code>agg()</code>, and <code>sort()</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.with_columns(
    year=pl.col("date").dt.year(),
    month=pl.col("date").dt.month(),
    weekday=pl.col("date").dt.weekday(),
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    downloads
    .with_columns(weekday=pl.col("date").dt.weekday())
    .group_by("weekday")
    .agg(avg_downloads=pl.col("value").mean())
    .sort("avg_downloads", descending=True)
)</pre>
</div>

## Exercise 6: String expressions

The code below shows the unique metric names from the GitHub source.
Names like `daily_issues_opened` are hard to read.
Transform them so that underscores are replaced with spaces and the result is title-cased (e.g., "Daily Issues Opened").

In [ ]:
github_metrics = metrics.filter(pl.col("source") == "github")
github_metrics.select("metric").unique().sort("metric")

**Optional extension:**

* Split each metric name into two new columns: `frequency` (the first word, e.g., "daily" or "total") and `measurement` (the rest, e.g., "issues opened").

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Use the <code>.str</code> namespace: <code>.str.replace_all()</code> and <code>.str.to_titlecase()</code>.<br>
&bull; For the extension, <code>.str.split("_")</code> returns a list column. Use <code>.list.first()</code> to get the first element.<br>
&bull; To get the remaining words, use <code>.list.slice(1)</code> followed by <code>.list.join(" ")</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    github_metrics
    .select("metric")
    .unique()
    .with_columns(
        clean_name=pl.col("metric").str.replace_all("_", " ").str.to_titlecase()
    )
    .sort("metric")
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    github_metrics
    .select("metric")
    .unique()
    .with_columns(
        frequency=pl.col("metric").str.split("_").list.first(),
        measurement=pl.col("metric").str.split("_").list.slice(1).list.join(" "),
    )
    .sort("metric")
)</pre>
</div>

## Exercise 7: Aggregation basics

Group `downloads` by `project` and calculate:

* the total number of downloads
* the mean daily downloads
* the maximum single-day download count
* the number of days with data

**Optional extension:**

* Group by both `project` and month, and find the 5 project-month combinations with the highest total downloads.

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Use <code>.group_by("project").agg(...)</code> with named expressions.<br>
&bull; Useful aggregation functions: <code>.sum()</code>, <code>.mean()</code>, <code>.max()</code>, and <code>pl.len()</code> for counting rows.<br>
&bull; For the extension, first add a <code>month</code> column with <code>.with_columns()</code>, then group by both columns.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">downloads.group_by("project").agg(
    total=pl.col("value").sum(),
    mean_daily=pl.col("value").mean(),
    max_daily=pl.col("value").max(),
    n_days=pl.len(),
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    downloads
    .with_columns(month=pl.col("date").dt.month())
    .group_by("project", "month")
    .agg(total=pl.col("value").sum())
    .sort("total", descending=True)
    .head(5)
)</pre>
</div>

## Exercise 8: Complete the pipeline

The pipeline below is missing several expressions (marked with `_____`).
Fill in the blanks to compute, for each project, the total downloads and the number of days where downloads exceeded 1,000.

In [ ]:
# (
#     downloads
#     .filter(_____)              # Keep only rows with more than 1,000 downloads
#     .group_by(_____)            # Group by project
#     .agg(
#         total=_____,            # Total downloads
#         n_days=_____,           # Number of days above 1,000
#     )
#     .sort(_____)                # Sort by total downloads, highest first
# )

**Optional extension:**

* Add the median downloads, the earliest date, and the latest date to the aggregation.

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; The filter condition is <code>pl.col("value") &gt; 1_000</code>.<br>
&bull; Group by <code>"project"</code>.<br>
&bull; Use <code>pl.col("value").sum()</code> for total and <code>pl.len()</code> for counting rows.<br>
&bull; Sort by <code>"total"</code> with <code>descending=True</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    downloads
    .filter(pl.col("value") &gt; 1_000)
    .group_by("project")
    .agg(
        total=pl.col("value").sum(),
        n_days=pl.len(),
    )
    .sort("total", descending=True)
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    downloads
    .filter(pl.col("value") &gt; 1_000)
    .group_by("project")
    .agg(
        total=pl.col("value").sum(),
        n_days=pl.len(),
        median=pl.col("value").median(),
        first_date=pl.col("date").min(),
        last_date=pl.col("date").max(),
    )
    .sort("total", descending=True)
)</pre>
</div>

## Exercise 9: Joining DataFrames

The two DataFrames below summarize PyPI downloads and GitHub stars per project.
Join them on `project` so that you can see each project's downloads alongside its GitHub stars.

In [ ]:
pypi_totals = (
    downloads
    .group_by("project")
    .agg(total_downloads=pl.col("value").sum())
)
pypi_totals

In [ ]:
github_stars = (
    metrics.filter(
        pl.col("source") == "github",
        pl.col("metric") == "total_reactions",
    )
    .group_by("project")
    .agg(total_stars=pl.col("value").max())
)
github_stars

**Optional extension:**

* Use an anti-join to find projects that have PyPI downloads but no GitHub star data. What could explain the mismatch?

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Use <code>pypi_totals.join(github_stars, on="project", how=...)</code>.<br>
&bull; A <code>"left"</code> join keeps all rows from the left DataFrame and fills in <code>null</code> where there's no match.<br>
&bull; An <code>"anti"</code> join returns rows from the left DataFrame that have *no* match in the right.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">pypi_totals.join(github_stars, on="project", how="left")</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">pypi_totals.join(github_stars, on="project", how="anti")</pre>
</div>

## Exercise 10: Putting it all together

Answer this question using a single method chain:

> *Which 5 GitHub projects had the most total activity (sum of all daily metrics) in 2026?*

Start from the full `metrics` DataFrame and use filter, group_by, agg, and sort.

**Optional extension:**

* Convert your solution to a lazy pipeline by replacing `pl.read_parquet(...)` with `pl.scan_parquet(...)` and adding `.collect()` at the end. Use `.explain()` (instead of `.collect()`) to inspect the query plan.

**Hints** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
&bull; Filter to <code>source == "github"</code> and metrics that start with <code>"daily_"</code>.<br>
&bull; Use <code>.str.starts_with("daily_")</code> to match metric names.<br>
&bull; Filter the date column to 2026 using <code>.dt.year()</code>.<br>
&bull; Group by <code>"project"</code>, aggregate with <code>.sum()</code>, sort descending, and take <code>.head(5)</code>.<br>
</div>

**Answer** *(highlight to reveal)*

<div style="color: #555; background-color: #555; padding: 8px; border-radius: 4px;">
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    metrics
    .filter(
        pl.col("source") == "github",
        pl.col("metric").str.starts_with("daily_"),
        pl.col("date").dt.year() == 2026,
    )
    .group_by("project")
    .agg(total_activity=pl.col("value").sum())
    .sort("total_activity", descending=True)
    .head(5)
)</pre>
Extension:<br>
<br>
<pre style="color: inherit; background: inherit; margin: 4px 0; padding: 0;">(
    pl.scan_parquet("data/metrics.parquet")
    .filter(
        pl.col("source") == "github",
        pl.col("metric").str.starts_with("daily_"),
        pl.col("date").dt.year() == 2026,
    )
    .group_by("project")
    .agg(total_activity=pl.col("value").sum())
    .sort("total_activity", descending=True)
    .head(5)
    .collect()
)</pre>
</div>